- src: kamaln7.swapfile
- src: geerlingguy.git
- src: geerlingguy.php
- src: geerlingguy.redis
- src: geerlingguy.varnish
- src: geerlingguy.nodejs
- src: geerlingguy.docker
- src: geerlingguy.composer
