---

- hosts: all
  vars_files:
    - vars/main.yml
  roles:
    - kamaln7.swapfile
    - geerlingguy.git
    - geerlingguy.redis
    - geerlingguy.varnish
    - geerlingguy.nodejs

  tasks:
    - name: Install make
      apt:
        name: build-essential
        state: present
    - name: Install libfontconfig
      apt:
        name: libfontconfig
        state: present
